# Site settings
title: "Rudy's Portfolio"
description: "Full Stack Developer & Tech Enthusiast - Personal Portfolio"
author: Rudy
url: "https://rudyrdx.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: assets/css
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
